[package]
name = "bballapp_backend"
version = "0.1.0"
edition = "2021"
authors = ["KwonJuHyeon <rnjstksaor@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
